version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27027:27017
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
volumes:
  mongodata: